version: '3.4'

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: Europe/Stockholm
    networks:
      - openvpn
    dns:
      - 209.222.18.222
      - 209.222.18.218
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn:/vpn
    command: '-f "" -d'

  transmission:
    image: dperson/transmission
    depends_on:
      - vpn
    environment:
      TZ: Europe/Stockholm
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /path/to/Transmission:/var/lib/transmission-daemon:Z
    labels:
      - "traefik.enable=true"
      - "traefik.port=9091"
      - "traefik.frontend.rule=Host:transmission" 

  sonarr:
    image: linuxserver/sonarr:preview
    depends_on:
      - vpn
      - transmission
      - jackett
    network_mode: "service:vpn"
    environment:
      TZ: Europe/Stockholm
    volumes:
      - /path/to/Sonarr/config:/config
      - /path/to/Sonarr/tv:/tv
      - /path/to/Transmission/downloads:/var/lib/transmission-daemon/downloads
    #ports:
    #  - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=8989"
      - "traefik.frontend.rule=Host:sonarr" 

  radarr:
    image: linuxserver/radarr
    depends_on:
      - vpn
      - transmission
      - jackett
    network_mode: "service:vpn"
    environment:
      TZ: Europe/Stockholm
    volumes:
      - /path/to/Radarr/config:/config
      - /path/to/Radarr/movies:/movies
      - /path/to/Transmission/downloads:/var/lib/transmission-daemon/downloads
    #ports:
    #  - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=7878"
      - "traefik.frontend.rule=Host:radarr"       

  bazarr:
    image: linuxserver/bazarr
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      TZ: Europe/Stockholm
    volumes:
      - /n/Bazarr/config:/config
      - /n/Radarr/movies:/movies
      - /n/Sonarr/tv:/tv
    #ports:
    #  - 6767:6767
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=6767"
      - "traefik.frontend.rule=Host:bazarr"

  jackett:
    image: linuxserver/jackett
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      TZ: Europe/Stockholm
    volumes:
      - /path/to/Jackett/config:/config
      - /path/to/Jackett/downloads:/downloads
    #ports:
    #  - 9117:9117
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=9117"
      - "traefik.frontend.rule=Host:jackett" 

  traefik:
    image: traefik:alpine
    depends_on:
      - transmission
      - sonarr
      - radarr
      - jackett
      - bazarr
    links:
      - vpn:transmission
      - vpn:sonarr
      - vpn:radarr
      - vpn:jackett
      - vpn:bazarr
    ports:
      - 80:80
    # - 8080:8080
    networks:
      - openvpn  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik"        
    command:
      - --api
      - --docker
      - --docker.exposedByDefault=false
    # - --logLevel=DEBUG

  unrar:
    build:
      context: ./cron/unrar
    depends_on:
      - transmission
    volumes:
      - /n/Transmission/downloads:/data
    restart: unless-stopped

networks:
  openvpn: